services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql-${NICKNAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:7.4.2
    container_name: redis-${NICKNAME}
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ./docker/redis:/data
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - default

networks:
  default:
    name: ${NICKNAME}
    driver: bridge
