# Database connection details
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  
  # JPA provider (optional, defaults to Hibernate)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  # Optional properties for customization
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
# Set to update or none based on your needs