spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ex1-hello-jpa
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
server:
  port: 8081
  # datasource:
  # url: jdbc:h2:file:./data/demo
  # driver-class-name: org.h2.Driver
  # username: sa
  # password:
  # hikari:
  #   maximum-pool-size: 10
  #   minimum-idle: 2
  #   auto-commit: true
  #   connection-timeout: 30000
  #   idle-timeout: 600000
  #   max-lifetime: 1800000
  # h2:
  #   console:
  #     enabled: true
  #     path: /h2-console
