services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql-${NICKNAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - '${MYSQL_PORT}:3306'
    networks:
      - default

networks:
  default:
    name: ${NICKNAME}
    driver: bridge
